name: Debug macOS (.app bundle)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '0.1.0'
        type: string
      timeout:
        description: 'timeout in seconds'
        required: true
        default: '30'
        type: string

jobs:
  debug_job:
    name: Debug on macOS (.app bundle)
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: |
          echo "version: ${{ github.event.inputs.version }}"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build
        run: |
          python build.py --version ${{ github.event.inputs.version }} --nodebug --dirmode

      - name: Install coreutils (timeout cmd needs this)
        if: runner.os == 'macOS'
        run: brew install coreutils

      - name: Rename, run and test (.app bundle)
        if: runner.os == 'macOS'
        run: |
          ls
          ls ./dist
          ls ./dist/WatermarkRemover || true
          echo "adding permission ..."
          chmod +x ./dist/WatermarkRemover.app/Contents/MacOS/WatermarkRemover
          echo "running ./scripts/run_unix.sh ..."
          ./scripts/run_unix.sh -a "./dist/WatermarkRemover.app/" -t ${{ github.event.inputs.timeout }}; echo $?
          echo "done"