name: Debug Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '0.4.1'
        type: string

jobs:
  debug_job:
    name: Debug on windows
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      #      - run: |
      #          echo "Log level: $LEVEL"
      #          echo "Tags: $TAGS"
      #          echo "Environment: $ENVIRONMENT"
      #        env:
      #          LEVEL: ${{ github.event.inputs.logLevel }}
      #          TAGS: ${{ github.event.inputs.tags }}
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          echo The version is ${{ github.event.inputs.version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build
        run: |
          python scripts/build.py

      - name: Rename .exe + run .exe
        run: |
          Write-Host "Current directory:"
          Get-ChildItem
          Write-Host ".\dist directory:"
          Get-ChildItem -Path ".\dist"
          Rename-Item -Path ".\dist\WatermarkRemover-wind32-${{ github.event.inputs.version }}.exe" -NewName "WatermarkRemover.exe"
          Write-Host "Current directory:"
          Get-ChildItem
          Write-Host ".\dist directory:"
          Get-ChildItem -Path ".\dist"
          Write-Host "starting .\dist\WatermarkRemover.exe ..."
          Start-Process -FilePath ".\dist\WatermarkRemover.exe"
          Write-Host "Waiting for 30s..."
          Start-Sleep -s 30
          Write-Host "Starting run_win.bat ..."
          Start-Process -FilePath ".\test_scripts\run_win.bat" -ArgumentList {".\dist\WatermarkRemover.exe"; "30";}
          Write-Host "Result: $?"
          Write-Host "Last exit code: $LastExitCode"
        shell: powershell
#        continue-on-error: true

#      - name: Test .exe
#        run: |
#          echo starting test script...
#          .\test_scripts\run_win.bat .\dist\WatermarkRemover.exe 30
#          echo Test result: %ERRORLEVEL%
#        shell: cmd